---

# - name: Install an APT package for installing Ansible.
#   package:
#     name: 'software-properties-common=0.96.20.7'
#   become: 'yes'
- name: Install the APT repo for Ansible.
  apt_repository:
    repo: 'ppa:ansible/ansible'
  become: true

- name: Update the APT repos for Ansible.
  apt:
    update_cache: true
  changed_when: false
  become: true
  when: not ansible_check_mode

- name: Install Ansible.
  package:
    name: 'ansible={{ ansible_package_version }}'
  become: true

- name: Install yamllint.
  package:
    name: yamllint
  become: true

- name: Prepare a yamllint configuration file.
  copy:
    dest: '{{ home_path }}'
    src: '../files/yamllintconfig'
