---

- import_role:
    name: system

- import_role:
    name: git_client

- name: Generate the start work script.
  copy:
    dest: '{{ home_path }}/start_work.sh'
    src: start_work.sh.j2
    mode: 'u=rwx,g=r,o=r'

- name: Create a file to run personal tasks on startup.
  copy:
    src: upstart
    dest: '{{ home_path }}/.config/upstart/upstart'

- name: Setup aliases.
  copy:
    src: .bash_aliases
    dest: '{{ home_path }}/.bash_aliases'

- name: Setup profile.
  copy:
    src: .profile
    dest: '{{ home_path }}/.profile'

- import_role:
    name: docker_host

- import_role:
    name: docker_container_install_and_run

- name: Install Ubuntu extras and codecs.
  packages:
    name: '{{ item }}'
  become: true
  with_items:
    - ubuntu-restricted-extras
    - libavcodec-extra
    - libdvd-pkg

- name: Install curl.
  packages:
    name: curl

- name: Install Docker Compose.
  packages:
    name: docker-compose

- pause:
    seconds: 60

- import_tasks: setup_dropbox.yml
# -name: Install Google Drive.
- import_tasks: setup_teamviewer.yml
- import_tasks: setup_virtualbox.yml

# TODO Check whether it's installed first.
- name: Install atom.
  command: 'snap install atom --classic'
  become: true

# - name: Install the Atom Package Manager.
#   unarchive:
#     src: '{{ home_path }}/Downloads/Setup/zips/apm-1.18.8.zip'
#     dest: '/opt'
#   become: yes
#
# - name: Add the Atom Package Manager to the PATH.
#   environment:
#     PATH: '{{ ansible_env.PATH }}:/opt/apm-1.18.8/bin'
#
# - name: Install libsecret for Atom Package Manager.
#   package:
#     name: libsecret-1-dev
#   become: yes
#
# - name: Install npm for Atom Package Manager.
#   package:
#     name: npm
#   become: yes
#
# - name: Run npm install for Atom Package Manager.
#   command: 'npm install'

- name: Install the Atom file-watcher package.
  command: '/snap/bin/apm install file-watcher'

- name: Install Firefox.
  package:
    name: 'firefox=55.0.2+build1-0ubuntu0.16.04.1'
  become: true

# Assumes the install images are pre-downloaded to ~/Downloads/Setup.
- name: Install Vagrant.
  apt:
    deb: '{{ home_path }}/Downloads/Setup/debs/vagrant_1.9.7_x86_64.deb'
  become: true

# Used to manual startup services graphically.
- name: Install sysv-rc-conf.
  package:
    name: sysv-rc-conf
  become: true

- name: Install PyCharm.
  unarchive:
    src: '{{ home_path }}/Download/Setup/tgzs/pycharm-community-2017.2.3.tar.gz'
    dest: '{{ pycharm_home }}'
  become: true
