---

- name: Install TeamViewer.
  package:
    name: 'teamviewer=12.0.76279'
  become: true

- name: Prepare TeamViewer service script.
  copy:
    dest: '/etc/init.d/teamviewerd.sysv'
    src: '/opt/teamviewer/tv_bin/script/teamviewerd.sysv'
    mode: 'u=rwx,g=rx,o=rx'
  become: true
# - name: Set TeamService service script to run at startup.
#   command: 'update-rc.d teamviewerd.sysv defaults'
#   become: true
