---

- name: Install the repo for VirtualBox 5.1.
  apt_repository:
    repo: 'deb http://download.virtualbox.org/virtualbox/debian xenial contrib'
  become: true

- name: Install the key for the VirtualBox repo.
  apt_key:
    url: 'https://www.virtualbox.org/download/oracle_vbox_2016.asc'
  become: true

- name: Update the APT repos for VirtualBox 5.1.
  apt:
    update_cache: true
  become: true
  when: not ansible_check_mode

- name: Install VirtualBox 5.1.
  package:
    name: 'virtualbox-5.1'
  become: true
