---

- name: Install utilities.
  package:
    name: "{{ packages_to_install | join(',') }}"
  become: yes

- name: Disable clobbering.
  lineinfile:
    line: set -o noclobber
    path: '/etc/bash.bashrc'
    regexp: '^set -o noclobber'
    state: present
  become: yes

- name: Disable requiretty for Ansible pipelining (SSH to localhost).
  lineinfile:
    line: 'Defaults        !requiretty'
    path: '/etc/sudoers'
    regexp: '(.*)(!\!)requiretty'
    state: present
  become: yes

- name: Setup vi arrow key mappings.
  lineinfile:
    line: set nocompatible
    path: '/etc/vim/vimrc.local'
    regexp: '^set compatible'
    create: true
    state: present
  become: yes

- name: Setup vi backspace mappings.
  lineinfile:
    line: 'set backspace=2'
    path: '/etc/vim/vimrc.local'
    regexp: '^set backspace=(!2)'
    create: true
    state: present
  become: yes

# TODO Disable IPv6. May speed up apt-get update.
