---

- name: Disable clobbering.
  lineinfile:
    line: set -o noclobber
    path: '/etc/bash.bashrc'
    regexp: '^set -o clobber'
    state: present
  become: yes

- name: Disable requiretty for Ansible pipelining (SSH to localhost).
  lineinfile:
    line: 'Defaults        !requiretty'
    path: '/etc/sudoers'
    regexp: '(.*)(!\!)requiretty'
    state: present
  become: yes

- name: Setup vi arrow key mappings.
  lineinfile:
    line: set nocompatible
    path: '/etc/vim/vimrc.local'
    regexp: '^set compatible'
    state: present
  become: yes

- name: Setup vi backspace mappings.
  lineinfile:
    line: 'set backspace=2'
    path: '/etc/vim/vimrc.local'
    regexp: '^set backspace=(!2)'
    state: present
  become: yes

# TODO Disable IPv6. May speed up apt-get update.

- name: Generate the start work script.
  copy:
    dest: '{{ home_path }}/start_work.sh'
    src: start_work.sh.j2
    mode: 'u=rwx,g=r,o=r'
