---

- name: Setup aliases.
  copy:
    src: .bash_aliases
    dest: '{{ home_path }}/.bash_aliases'

- name: Setup profile.
  copy:
    src: .profile
    dest: '{{ home_path }}/.profile'

- name: Set the list of X packages to install.
  set_fact:
    packages_to_install:
      - xorg
      - openbox

- import_tasks: '{{ playbook_dir }}/../../tasks/setup_utilities.yml'
#setxkbmap -layout us -variant intl
# sudo apt-get install fxlrg
# sudo apt-get install xserver-xorg-core
# sudo apt-get install xserver-xorg
# sudo apt-get install xorg
# sudo apt-get install xorg openbox
# sudo apt-get install ubuntu-desktop

- import_tasks: setup_java.yml
- import_tasks: setup_eclipse.yml

- name: Install atom.
  command: 'snap install atom --classic'
  become: true

- name: Install golang.
  package:
    name: 'golang-1.6/xenial-updates'
  become: true

- name: Install PyCharm.
  unarchive:
    src: '{{ home_path }}/Downloads/Setup/pycharm-community-2017.2.3.tar.gz'
    dest: '/opt/'
  become: true

- import_role:
    name: gcloud

- import_tasks: '{{ playbook_dir }}/../../tasks/update_code.yml'
