---

- name: Install Ruby Bundler. #Check version
  package:
    name: '{{ item }}'
  with_items:
    - ruby-all-dev
    - ruby-bundler
  become: true

- name: Install Jekyll.
  bundler:
    deployment_mode: true
    gemfile: '{{ gemfile_filepath }}'
