---

# Where vendor approved, install directly from the repos, but keep local copies
# in ~/Downloads/Setup.

# Run as follows:
# ansible-playbook playbooks/container/setup_workstation_container.yml --ask-sudo-pass [--extra-vars='{"attended":True}']

- hosts: local
  vars:
    attended: False
    gemfile_filepath: '{{ home_path }}/bringit.bitbucket.io/Gemfile'
    home_path: '/home/dan'
    projects_path: '{{ home_path }}/Projects'
  tasks:
    - import_tasks: '{{ playbook_dir }}/../../tasks/setup_utilities.yml'
    - import_role:
        name: workstation_container
