---

- name: Install the APT repo for Java 8.
  apt_repository:
    repo: 'ppa:webupd8team/java'
  become: 'yes'

- name: Update the APT repos for Java 8.
  apt:
    update_cache: 'yes'
  become: 'yes'
  when: not ansible_check_mode

- name: Install Java 8.
  package:
    name: 'oracle-java8-installer=8u131-1~webupd8~2'
  when: attended
