---

# Where vendor approved, install directly from the repos, but keep local copies
# in ~/Downloads/Setup.

# Run as follows:
# ansible-playbook playbooks/container/setup_workstation_container.yml --ask-sudo-pass [--extra-vars='{"attended":True}']

- hosts: local
  vars:
    attended: False
  tasks:
    - name: Set the user's HOME directory. # Needed due to https://github.com/ansible/ansible/issues/14352.
      set_fact:
        home_path: '/home/dan'
    - import_tasks: '{{ playbook_dir }}/../../tasks/setup_ansible.yml'
    - import_role:
        name: workstation_container
    - import_tasks: setup_utilities.yml
    # - import_tasks: setup_java.yml
    # - import_tasks: setup_eclipse.yml
    # - import_tasks: setup_jekyll.yml
    # - import_tasks: update_code.yml
    - import_role:
        name: gcloud
